target "eService" do
pod 'UINavigationItem+Margin'
pod 'FontAwesomeKit/IonIcons'
pod 'JDStatusBarNotification'
pod 'YYWebImage'
pod 'CocoaSecurity'
pod 'FCUUID'
pod 'AliyunOSSiOS', '~> 2.6.0'
pod 'WechatOpenSDK'
pod 'Popover.OC'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'AppSettings'
pod 'MWPhotoBrowser'
pod 'TOCropViewController'
#pod 'imglyKit', '~> 5.0.7'
#pod 'WebViewJavascriptBridge', '~> 5.0'
#pod 'BaiduMapKit'
#pod 'TencentMapSdk'
#pod 'LFImagePickerController', '1.0.9'
end
